package com.egov.authservice;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "credentials") // for mongodb
public class Credential
{
    @Id
    String id; // this id will be generated by mongodb
    String username;
    String password;
}
