
#INSTALLATION OF THE OPERATING SYSTEM
FROM openjdk:17-jdk

LABEL authors="mkb"

#PLACEMENT OF THE EXECUTABLE [MICROSERVICE] ON THE IMAGE
COPY target/auth-service-dev.jar auth-service.jar

#EXPOSE PORTS FOR INCOMING TRAFFIC - HOST_PORT:CONTAINER_PORT
EXPOSE 8090:8090

#INSTALLING UTILITIES
# RUN apt-get update
# RUN apt-get install -y gcc
# RUN apt-get install -y curl

#ENTRYPOINT OF THE CONTAINER THROUGH THE MICROSERVICE
ENTRYPOINT ["java","-jar","auth-service.jar"]